spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kopring
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true